### ISSUE TITLE
fix(feat): improvements of UI/UX

### ISSUE THREAD

**Issue by kaizenics** [WenDEVLIFE/Quizz-Game-App-Java#1]
suggestions: 

- avoid using button animation
- use sans fonts
- keep using low contrast colors (2-3 colors minimum) and make it consistent
- background images should not be stretched
- improve UX (especially in navigation)

comments/suggestions:

- the functions is good, keep it up!
- it is okay that you put a background image in the first page (intro) but in the second and third page, i suggest that you should remove it and replace a trademark color of the app
- make it simpler. if the app is simple and easy, it more likely comprehensible and beautiful to the user

**Comment by WenDEVLIFE** [comment]
Done
